### ISSUE TITLE
bug(ui): Page crashes if the authentication expires while the page is open.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#1241]

**Comment by elliotcourant** [comment]
```
React ErrorBoundary Error: ((intermediate value)(intermediate value)(intermediate value) || []).map is not a function
  at FundingSchedulesView(./ui/components/FundingSchedules/FundingSchedulesView.tsx:10:51)
  at RenderedRoute(./node_modules/react-router/dist/index.js:652:5)
  at Routes(./node_modules/react-router/dist/index.js:1099:5)
  at nF(./ui/AuthenticatedApp.tsx:21:45)
  at Application(./ui/Application.tsx:11:34)
  at InnerContextProvider(./node_modules/@ebay/nice-modal-react/lib/esm/index.js:307:23)
  at NiceModal.Provider(./node_modules/@ebay/nice-modal-react/lib/esm/index.js:316:23)
  at SnackbarProvider(./node_modules/notistack/dist/notistack.esm.js:720:24)
  at LocalizationProvider(./node_modules/@mui/x-date-pickers/LocalizationProvider/LocalizationProvider.js:15:5)
  at InnerThemeProvider(./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:10:17)
  at sr(./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:35:5)
  at dr(./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:30:5)
  at Bn(./node_modules/react-router/dist/index.js:1031:15)
  at BrowserRouter(./node_modules/react-router-dom/dist/index.js:224:5)
  at QueryClientProvider(./node_modules/react-query/es/react/QueryClientProvider.js:32:21)
  at ErrorBoundary(./node_modules/@sentry/react/esm/errorboundary.js:26:47)
TypeError: ((intermediate value)(intermediate value)(intermediate value) || []).map is not a function
  at useBankAccountsSink(./ui/hooks/bankAccounts.ts:19:42)
  at useSelectedBankAccountId(./ui/hooks/bankAccounts.ts:36:47)
  at useFundingSchedulesSink(./ui/hooks/fundingSchedules.ts:12:33)
  at FundingSchedulesView(./ui/components/FundingSchedules/FundingSchedulesView.tsx:10:51)
  at Xh(./node_modules/react-dom/cjs/react-dom.production.min.js:167:137)
  at dj(./node_modules/react-dom/cjs/react-dom.production.min.js:197:258)
  at Wk(./node_modules/react-dom/cjs/react-dom.production.min.js:292:88)
  at Vk(./node_modules/react-dom/cjs/react-dom.production.min.js:280:389)
  at Uk(./node_modules/react-dom/cjs/react-dom.production.min.js:280:320)
  at Jk(./node_modules/react-dom/cjs/react-dom.production.min.js:280:180)
  at Ok(./node_modules/react-dom/cjs/react-dom.production.min.js:271:88)
  at Hk(./node_modules/react-dom/cjs/react-dom.production.min.js:268:429)
  at J(./node_modules/scheduler/cjs/scheduler.production.min.js:13:203)
  at R(./node_modules/scheduler/cjs/scheduler.production.min.js:14:128)
```

**Comment by elliotcourant** [comment]
Have the /user/me query clear the entire react query state if we get an unauthorized. This should fix it hopefully

**Comment by elliotcourant** [comment]
I think to make this work I would need to change how I have react-query handling error responses from the server.

Right now it will throw on a `500` status code, but will simply return the error body in other scenarios.

I'm not sure yet what would be a good approach for improving this at this time.
