### ISSUE TITLE
bug(ui): Page can crash on the funding schedules view if it is loaded first.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#1244]
This is due to a potential missing balance when calculating the estimated safe to spend.

**Comment by elliotcourant** [comment]
```
React ErrorBoundary Error: Cannot read properties of undefined (reading 'safe')
  at <object>.Fragment.ListItem.children(./ui/components/FundingSchedules/FundingScheduleListItem.tsx:89:28)
  at <anonymous>(./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:35:17)
  at ListItem(./node_modules/@mui/material/ListItem/ListItem.js:137:17)
  at FundingScheduleListItem(./ui/components/FundingSchedules/FundingScheduleListItem.tsx:20:39)
  at <anonymous>(./node_modules/@emotion/react/dist/emotion-element-cbed451f.browser.esm.js:35:17)
  at List(./node_modules/@mui/material/List/List.js:51:17)
  at FundingSchedulesView(./ui/components/FundingSchedules/FundingSchedulesView.tsx:10:51)
  at RenderedRoute(./node_modules/react-router/dist/index.js:652:5)
  at Routes(./node_modules/react-router/dist/index.js:1099:5)
  at nF(./ui/AuthenticatedApp.tsx:21:45)
  at Application(./ui/Application.tsx:11:34)
  at InnerContextProvider(./node_modules/@ebay/nice-modal-react/lib/esm/index.js:307:23)
  at NiceModal.Provider(./node_modules/@ebay/nice-modal-react/lib/esm/index.js:316:23)
  at SnackbarProvider(./node_modules/notistack/dist/notistack.esm.js:720:24)
  at LocalizationProvider(./node_modules/@mui/x-date-pickers/LocalizationProvider/LocalizationProvider.js:15:5)
  at InnerThemeProvider(./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:10:17)
  at sr(./node_modules/@mui/private-theming/ThemeProvider/ThemeProvider.js:35:5)
  at dr(./node_modules/@mui/system/esm/ThemeProvider/ThemeProvider.js:30:5)
  at Bn(./node_modules/react-router/dist/index.js:1031:15)
  at BrowserRouter(./node_modules/react-router-dom/dist/index.js:224:5)
  at QueryClientProvider(./node_modules/react-query/es/react/QueryClientProvider.js:32:21)
  at ErrorBoundary(./node_modules/@sentry/react/esm/errorboundary.js:26:47)
TypeError: Cannot read properties of undefined (reading 'safe')
  at <object>.Fragment.ListItem.children(./ui/components/FundingSchedules/FundingScheduleListItem.tsx:89:28)
  at Xh(./node_modules/react-dom/cjs/react-dom.production.min.js:167:137)
  at Wk(./node_modules/react-dom/cjs/react-dom.production.min.js:290:337)
  at Vk(./node_modules/react-dom/cjs/react-dom.production.min.js:280:389)
  at Uk(./node_modules/react-dom/cjs/react-dom.production.min.js:280:320)
  at Jk(./node_modules/react-dom/cjs/react-dom.production.min.js:280:180)
  at Ok(./node_modules/react-dom/cjs/react-dom.production.min.js:271:88)
  at Hk(./node_modules/react-dom/cjs/react-dom.production.min.js:268:429)
  at J(./node_modules/scheduler/cjs/scheduler.production.min.js:13:203)
  at R(./node_modules/scheduler/cjs/scheduler.production.min.js:14:128)
```
