### ISSUE TITLE
bug: Pod crashing in `v0.6.9` release.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#395]
```
migrations panic: 1 error(s) decoding:
migrations * cannot parse 'ListenPort' as int: strconv.ParseInt: parsing "tcp://10.200.6.159:4000": invalid syntax
migrations goroutine 1 [running[]:
migrations github.com/monetr/monetr/pkg/config.LoadConfiguration(_)
migrations     /build/pkg/config/configuration.go:307 +0x29d
migrations github.com/monetr/monetr/pkg/internal/cmd.getDatabaseCommandConfiguration()
migrations     /build/pkg/internal/cmd/migrate.go:121 +0x46
migrations github.com/monetr/monetr/pkg/internal/cmd.glob..func3(0x2770960, {0x1683118, 0x0, 0x0})
migrations     /build/pkg/internal/cmd/migrate.go:43 +0x90
migrations github.com/spf13/cobra.(*Command).execute(0x2770960, {0x27b6c38, 0x0, 0x0})
migrations     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
migrations github.com/spf13/cobra.(*Command).ExecuteC(0x276ff60)
migrations     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
migrations github.com/spf13/cobra.(*Command).Execute(...)
migrations     /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
migrations main.main()
migrations     /build/pkg/cmd/main.go:25 +0xfa
```

**Comment by elliotcourant** [comment]
Resolved by 9e5e067dd26bf5895329d0dd797175964332c12b hopefully
