### ISSUE TITLE
bug: PGAdmin not starting up properly for local development.

### ISSUE THREAD

**Issue by elliotcourant** [monetr/monetr#514]
```

2021-12-22 22:33:57,530: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:33:57 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:02,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:02 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:07,530: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:07 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:12,530: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:12 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:17,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:17 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:22,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:22 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:27,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:27 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:32,532: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:32 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:37,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:37 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:42,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:42 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:47,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:47 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:52,530: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:52 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:34:57,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:34:57 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:35:02,532: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:35:02 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:35:07,530: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:35:07 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:35:12,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:35:12 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
2021-12-22 22:35:17,531: ERROR    pgadmin:    module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1514, in full_dispatch_request
    rv = self.preprocess_request()
  File "/venv/lib/python3.9/site-packages/flask/app.py", line 1857, in preprocess_request
    rv = self.ensure_sync(before_func)()
  File "/pgadmin4/pgadmin/__init__.py", line 787, in before_request
    login_user(user)
  File "/venv/lib/python3.9/site-packages/flask_security/utils.py", line 145, in login_user
    if not _login_user(user, remember):  # pragma: no cover
  File "/venv/lib/python3.9/site-packages/flask_login/utils.py", line 188, in login_user
    user_logged_in.send(current_app._get_current_object(), user=_get_user())
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in send
    return [(receiver, receiver(sender, **kwargs))
  File "/venv/lib/python3.9/site-packages/blinker/base.py", line 266, in <listcomp>
    return [(receiver, receiver(sender, **kwargs))
  File "/pgadmin4/pgadmin/__init__.py", line 543, in on_user_logged_in
    if not config.AUTO_DISCOVER_SERVERS:
AttributeError: module 'config' has no attribute 'AUTO_DISCOVER_SERVERS'
172.17.0.1 - - [22/Dec/2021:22:35:17 +0000] "GET /login HTTP/1.1" 500 119 "-" "kube-probe/1.20"
```

**Comment by elliotcourant** [comment]
Given the migration to a docker compose setup, it might not be worth addressing this at all.
